### ISSUE TITLE
Problem with .travis.dist.yml

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#10]
In #5 we moved to dockered selenium-firefox execution. But it seems that the final .travis.dist.yml changes are a non-working version. Basically:

- if the docker container is launched BEFORE `moodle-plugin-ci install` then, the later, is unable to complete the moodle.git clone operation. See [this travis build](https://travis-ci.org/github/stronk7/moodle-local_codechecker/builds/707189114) and the [changes applied](https://github.com/stronk7/moodle-local_codechecker/commit/13f026197d8811f8a9eea33495ac0685b5d541f0) (following the `.travis.dist.yml` advise).
- Only if the docker container is launched AFTER `moodle-plugin-ci install` it's possible to get it working. See [this travis build](https://travis-ci.org/github/stronk7/moodle-local_codechecker/builds/707191870) and [the changes applied](https://github.com/stronk7/moodle-local_codechecker/commit/5759e3c3783ac7bdc21e2feb858ac102783675ae).

So, this issue is about to fix that (make a really working `.travis.dist.yml` file). And, maybe (optional) to consider to move all this stuff, and also the nvm / nodejs  one (see #7) to within `moodle-plugin-ci install`. Both are just "distractions", the plugin developer shouldn't need to modify all that stuff, ideally install should provide all (IMO).

Ciao :-)

**Comment by kabalin** [comment]
I remember I kept docker container run as last item in install step for a reason :) Anyway, I don't mind having it within install, although, may be a better place for it within behat command (like selenium jar execution used to be) along with php server (already there)?

**Comment by mudrd8mz** [comment]
> is unable to complete the moodle.git clone operation

Just to confirm this is the problem I was experiencing a few days ago when I tried to use the travis.dist in my own plugin.

**Comment by kabalin** [comment]
> In #5 we moved to dockered selenium-firefox execution.
Just to note in #5 we had a fix for Firefox container version, the actual change was made in https://github.com/blackboard-open-source/moodle-plugin-ci/pull/107

**Comment by stronk7** [comment]
> Just to note in #5 we had a fix for Firefox container version, the actual change was made in [blackboard-open-source/moodle-plugin-ci#107](https://github.com/blackboard-open-source/moodle-plugin-ci/pull/107)

Yeah, you are correct, I became confused with our #5 , https://github.com/blackboard-open-source/moodle-plugin-ci/pull/99 and everything else. And did the same in the CHANGELOG issue () that I'm amending right now.

BTW, oftopic, just saw that, curiously... while we add firefox for everybody (`.travis.dist.yml`), curiously we use chrome for out own tests of this repo (`.travis.yml`). Caused some fun here :-)

**Comment by stronk7** [comment]
> I remember I kept docker container run as last item in install step for a reason :) Anyway, I don't mind having it within install, although, may be a better place for it within behat command (like selenium jar execution used to be) along with php server initialisation (already there)?

I really think, as commented in the issue description... that all that stuff should be kept away from developers. In an ideal world, they should be able to just define the jobs combos (branch, db...) they want to run and then let `moodle-plugin-ci install` to do all the work. So they don't have to mind about nvm, npm, docker or anything else.

I'm aware we are not near to that, just painting the (my) ideal picture.

In fact, it's something that we need to be really careful, because it's also something that, maybe doesn't correspond to all jobs, but just to the behat ones (for example), or in other cases (for example, nvm / nodejs, or codechecker...) something similar happens, each job should install exclusively what is needed for it.

Anyway, this belongs to other, future issues.
