### ISSUE TITLE
Rename plugin build directory variable to a generic approach

### ISSUE THREAD

**Issue by adpe** [moodlehq/moodle-plugin-ci#105]
Hi @stronk7 

It's somehow confusing, when you are creating a CI/CD configuration file for GitLab and you must set the following variable `TRAVIS_BUILD_DIR` so that the "Install plugins" command will not fail.

Would be good to rename stuff, as not only Travis CI exists out there. Will make a PR soon.

Greets
Adrian

**Comment by stronk7** [comment]
Closing this now that #110 has been merged, thanks!
