### ISSUE TITLE
CODECHECKER_IGNORE_NAMES / CODECHECKER_IGNORE_PATHS does not appear to work

### ISSUE THREAD

**Issue by gjb2048** [moodlehq/moodle-plugin-ci#107]
RE: https://github.com/moodlehq/moodle-plugin-ci/issues/104

Was 'Closed' (so creating a new issue) but followed the advice and the environment variables in GitHub actions are having no effect:

https://github.com/gjb2048/moodle-format_topcoll/runs/2839262518?check_suite_focus=true#step:10:7 -> https://github.com/gjb2048/moodle-format_topcoll/runs/2839262518?check_suite_focus=true#step:10:59

As you can see, I've tried both methods as per the documentation (https://github.com/moodlehq/moodle-plugin-ci/blob/master/docs/GHAFileExplained.md): https://github.com/gjb2048/moodle-format_topcoll/actions/runs/942886613/workflow#L48-L84

Thanks,

Gareth

P.S. Ping @kabalin please.

**Comment by kabalin** [comment]
Sorry @gjb2048 , my bad. Those command related env vars need to be defined in the install step, not at actual command
(per https://github.com/moodlehq/moodle-plugin-ci/blob/master/src/Command/InstallCommand.php#L183-L209). Can you try again? (BTW your IGNORE_* globals are [at wrong section](https://github.com/gjb2048/moodle-format_topcoll/actions/runs/942886613/workflow#L56-L57), they need to be in where you call install command, i.e. in the next step)

**Comment by gjb2048** [comment]
@kabalin Thank you so much!  That worked, I do appreciate your time and will have a go at updating the docs to help.

**Comment by kabalin** [comment]
> @kabalin Thank you so much! That worked, I do appreciate your time and will have a go at updating the docs to help.

No probs, done that already #108
