### ISSUE TITLE
Mustache lint check complains about ES6

### ISSUE THREAD

**Issue by marinaglancy** [moodlehq/moodle-plugin-ci#113]
The following elements in Mustache templates fail the mustache check:

1.
    const square = x => x*2;

2.
    let v = `some ${string}`;

(Parsing error: Unexpected character '`')

**Comment by kabalin** [comment]
The reported problem concerns backtick in JS snippet within Mustache template, as I understood? I tested this using:
```
{{#js}}
    const a = 'b';
    var c = `hello ${a}`;
    window.console.log(c);
{{/js}}
```
Does not seem the case any more (may be becasue JS in template is linted now).

**Comment by andrewnicols** [comment]
It was always linted but we recently changed the rules that it was linted
under to allow ESM
