### ISSUE TITLE
Behat step fails with latest chrome selenium 3.141.59-20210729

### ISSUE THREAD

**Issue by justusdieckmann** [moodlehq/moodle-plugin-ci#121]
After getting errors in the behat step today (https://github.com/learnweb/moodle-mod_moodleoverflow/runs/3190196110?check_suite_focus=true#step:12:138), I tested it on my local machine, and running the tests with chrome selenium 3.141.59-20210713 succeeds, while running behat with chrome selenium 3 (.141.59-2021729) fails with the same error as the github action workflow:
```
The Selenium or WebDriver server is not running. You must start it to run tests that involve Javascript.
See https://docs.moodle.org/dev/Running_acceptance_test for more information.

The following debugging information is available:
. Could not open connection: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["disable-web-security","unlimited-storage"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","tags":["be0c3bcb73ea","PHP 7.4.16"],"chromeOptions":{"args":["disable-web-security","unlimited-storage"]},"browser":"chrome","marionette":null,"ignoreZoomSetting":false,"name":"Behat feature suite"}}

Operation timed out after 30001 milliseconds with 0 bytes received

* line 70 of /vendor/behat/mink/src/Session.php: call to OAndreyev\Mink\Driver\WebDriver->start()
* line 304 of /lib/tests/behat/behat_hooks.php: call to Behat\Mink\Session->start()
* line 293 of /lib/tests/behat/behat_hooks.php: call to behat_hooks->start_session()
* line 353 of /lib/tests/behat/behat_hooks.php: call to behat_hooks->restart_session()
* ...
```
(As a comparison, this workflow passed two hours earlier and was still using the selenium image 20210713, as told by the image hash: https://github.com/learnweb/moodle-mod_moodleoverflow/runs/3189275095?check_suite_focus=true#step:12:126)

Might it be a good idea to cap the selenium chrome image to 3.141.59-20210713 as a quick fix?
It appears firefox works fine in the latest selenium image.

**Comment by paulholden** [comment]
Thanks @justusdieckmann - we've also been wrestling with this issue internally today, thanks for creating this issue

**Comment by justusdieckmann** [comment]
Thank you for the fast response!

**Comment by kabalin** [comment]
Another workaround is to use firefox in CI for now, as it is not affected.

The issue is coming from Chromium, which has been upgraded to version 92 in 3.141.59-20210729 (from 91 in 3.141.59-20210713), there is also performance issue associated with this version: https://github.com/SeleniumHQ/docker-selenium/issues/1346

**Comment by kabalin** [comment]
Underlying Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1228625

**Comment by kabalin** [comment]
Underlying Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1228625
