### ISSUE TITLE
Towards a new major version 4

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#151]
Copied from a discussion elsewhere, just registering it here for further comments and planning:

> ...
> Maybe:
> 
> 1. We should consider to start working in a new major (4.0.0) release, coming with:
>     - move php mis requirement to php 7.3 (or 7.4). That will allow people to continue testing Moodle 3.6.4 ( or 3.8.3) and up (for older versions the 3.x series still will be working).
>     - updated components (symfony and friends).
>     - move to pcov for coverage maybe
>     - update phpunit/self tests…
> 2. Still, not matter the work in master towards that 4.0.0 new version, if we need to update anything in stables… we always can create a “3.x” branch and apply incremental changes there.
> 
> My main point is to move away from current php 7.0 compatibility (Moodle 3.0.1) that is forcing us to keep other tools (codechecker, symfony…) using really old stuff and, at some point, we’ll face real problems (for example with php81).

**Comment by stronk7** [comment]
Just experimenting:

[![](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%207.2%2C%20supporting%20Moodle%203.4%20and%20later%20releases)](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%207.2%2C%20supporting%20Moodle%203.4%20and%20later%20releases/vote)
[![](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%207.3%2C%20supporting%20Moodle%203.6.4%20and%20later%20releases)](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%207.3%2C%20supporting%20Moodle%203.6.4%20and%20later%20releases/vote)
[![](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%207.4%2C%20supporting%20Moodle%203.8.3%20and%20later%20releases)](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%207.4%2C%20supporting%20Moodle%203.8.3%20and%20later%20releases/vote)
[![](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%208.0%2C%20supporting%20Moodle%203.11.6%20and%20later%20releases)](https://api.gh-polls.com/poll/01FS7K69XDZ4817NJ7RBD82SZ2/PHP%208.0%2C%20supporting%20Moodle%203.11.6%20and%20later%20releases/vote)

**Comment by stronk7** [comment]
My personal preference is to go up to PHP 7.4, because it covers all current supported Moodle versions and because it's the currently minimum supported PHP version.

Though I don't oppose to PHP 7.3 either, given it's the current required version for Moodle 3.11 and 4.0.

**Comment by brendanheywood** [comment]
Can I suggest you move away from just master and have branches for stables so that we can still run ci on old plugins and keep their ci green even if we do minor things to them. We maintain lots of stuff which we support on out of support core versions. This might need to be reflected in the moodlecheck and codechecker plugins as needed too.

To reduce the overhead can I also suggest using branch names tracking the stables where compatibility started? ie we've slowly converged onto a branch strategy where we only fork new branches when we need to. So we might have a plugin branch MOODLE_35_STABLE which works on 3.5, 3.6, 3.7 and only then have MOODLE_38_STABLE which covers 3.8 - 3.11 etc. Or do it for each LTS version?

**Comment by stronk7** [comment]
Hi Brendan,

the creation of the new 4.x series (with raised PHP requirements) doesn't imply that the previous series (2.x, 3.x) will stop working. As far as you are using explicitly them (and not `dev-master`), everything should continue working the same:

```
composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
```

Just, people wanting to jump to the new version, will have to adjust their "matrix" of jobs and bump to `^4`.

Also, as stated in point 2 of the description... if once the 4.x series has started... we want to "backport" any change to the previous series, then and only then, it's when we'll create the `3.x` branch in the repo, to put the new stuff and tag new 3.x releases there. I don't think we need to branch in advance, cannot see any benefit on it.

So, for example, for your example above... for your 35_STABLE branch (which works for 3.5, 3.6 and 3.7), you can continue using the current `^3` moodle-plugin-ci. In fact, you can also continue using it for your 38_STABLE branch (current version supports everything till 4.0).

But then, for Moodle 4.1 (maybe LTS), with raised requirements to php74 (and supporting also php81), it's when you'll have to jump to `^4` (if you want to run php81 tests).

In any case, the important point is that the old series (2.x and 3.x) will continue working 100% as they are now. In fact there are a good number of plugins still using `^2`and that never has been a problem.

Ciao :-)

**Comment by stronk7** [comment]
A very, very earlier sneak preview of what could become next v4 is available here:

https://github.com/moodlehq/moodle-plugin-ci/compare/master...stronk7:moodle-plugin-ci:try_symfony_54

Note it's still WIP, but basically I've got all self-tests passing, next steps will be about to try it against real plugins.

Main features are:

- Bump to Symfony 5.4, that supports PHP 7.4 and up.
- (because of the above, PHP 7.4 will be the lowest version supported).
- Can be used for MOODLE_38_STABLE and up.
- All internal dependencies (phpunit, behat, psalm, php-cs-fixer...) have been updated to current ones.
- It's [passing perfectly](https://github.com/stronk7/moodle-plugin-ci/actions/runs/3937559417) but with PHP 8.1 because Moodle's core is still not 100% ready. Hopefully, soon it will be (being progressed @ [hMDL-73016](https://tracker.moodle.org/browse/MDL-73016).
- Various internals have been changed / simplified, there was some mix of different ways to invoke shells and friends. Still I think that they can be streamlined more, but not as part of this issue.
- Both Selenium 3 and Selenium 4 working (but 4 fails with MOODLE_38_STABLE). Future improvement may be to make it configurable.
- Aggressive coding-style changes towards PSR-12 compliance, and strong typing making Psalm 100% happy.
- And more things here and there that I've been fixing in spare time over the previous months. Really the changes are huge!

TODO:

- Add more testing coverage.
- Fix a couple of commands that still need a little bit of love.
- Document everything.
- Test, test, test.
- Party.

While it's being worked on, it can be tested by using this in your GHA/Travis files:

```
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index cb34950..560fc9b 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -103,10 +103,14 @@ jobs:
           extensions: ${{ matrix.extensions }}
           ini-values: max_input_vars=5000
           coverage: none
+        env:
+          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Initialise moodle-plugin-ci
         run: |
-          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
+          composer create-project -n --stability=dev --prefer-dist \
+              --repository="{\"url\": \"https://github.com/stronk7/moodle-plugin-ci.git\", \"type\": \"vcs\"}" \
+              moodlehq/moodle-plugin-ci ci dev-try_symfony_54
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
```

And that's it. More coming soon.

Ciao :-)

**Comment by stronk7** [comment]
What do you think if I straight push the `try_symfony_54` branch on top of master, so we can continue dev there?

https://github.com/moodlehq/moodle-plugin-ci/compare/master...stronk7:moodle-plugin-ci:try_symfony_54

All the own tests and some I've run against my repo (codechecker...) are passing ok, so we can prepare some early release (alpha, beta...) to allow people to try the switch from v3 to v4.

Of course, there is work to do so (document everything, requirements... write the upgrade docos...) but I think it's really ready to start sharing a little bit that stuff.

Also, we would create a `3.x` branch right now, so any bug fix will be applied there, and any new 3.x.y version will be, also, released there (forward / back porting everything till 4.0.0 final is released).

Thoughts?

**Comment by ewallah** [comment]
Just mentioning that PHP 7.4 is [end of life](https://www.php.net/eol.php). Support stopped on November 28th, 2022.

**Comment by stronk7** [comment]
> Just mentioning that PHP 7.4 is [end of life](https://www.php.net/eol.php). Support stopped on November 28th, 2022.

Yeah, but we need to support supported Moodle versions, and with our 3.9 - 4.1 supporting PHP 7.4, it would be crazy to ban that PHP version. So PHP 7.4 was the maximum raise we could apply this time.

Ciao :-)

**Comment by stronk7** [comment]
FYI all the stuff previously in the `try_symfony_54` branch (now deleted) has been added to master, on top of latest release `3.4.6`.

Also, the `3.x` branch has been created so any bug fix into the `^3` series will be applied there.

Next steps:
- Document all the v4 details, migration, changes.
- Test, test, test (and share about how to test).
- Make an initial v4.0.0 release, so people can, easily, go upgrading to it.

Ciao :-)

**Comment by stronk7** [comment]
So, just changing this in GHA:
{code}
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index cb34950..13f5f4d 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,7 +106,7 @@ jobs:
 
       - name: Initialise moodle-plugin-ci
         run: |
-          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
+          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci dev-master
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
{code}

It's not possible to run the new version for testing purposes.

For example: https://github.com/stronk7/moodle-local_codechecker/actions/runs/4151130360

(note that all runs < php 7.4 have failed, that's expected)

Ciao :-)

**Comment by scara** [comment]
Hi @stronk,
> It's not possible to run the new version for testing purposes.

is it possible to do a conditional run based on the Moodle _branch_ being under testing?
I'm thinking to those ones still ("bravely" :wink:) playing with mono-branch repo strategy for their plugins.

Do you think we should play with `${{ matrix.moodle-branch }}` to condition the entire _step_ or, if possible, to condition the `run` own logics? Kind of:
```yaml
      - name: Initialise moodle-plugin-ci
        run: |
          [[ "${{ matrix.moodle-branch }}" = "master" ]] \
               && composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4 \
               || composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
```
I'm not quite familiar with GHA options.

TIA,
Matteo

**Comment by stronk7** [comment]
Hi,

> It's not possible to run the new version for testing purposes.

Grrr, that was a typo. Obviously I meant to say "It's NOW possible to run..." like the [local_codechecker example](https://github.com/stronk7/moodle-local_codechecker/actions/runs/4151130360) was showing.

> is it possible to do a conditional run based on the Moodle branch being under testing?

And yes, that's quite possible. In fact it was documented (for Travis) in the [2.x => 3.x Upgrading guide](https://moodlehq.github.io/moodle-plugin-ci/UPGRADE-3.0.html). I'm working on a docs branch right now to complete the change log, the new 3.x => 4.x guide and other small changes.

Personally I think that MOODLE_38_STABLE with PHP 7.4 is old enough, so I won't be using such conditional installation but, for sure, there will be people interested into keeping their unique dev/release branches supporting a wider range or versions, so that will be useful for them.

I want to make the 1st draft of the docs along this (Feb 13th) week... let's see.

Thanks!

**Comment by stronk7** [comment]
It has been a long trip... but finally, moodle-plugin-ci 4.0.0 has been released, yay!

https://github.com/moodlehq/moodle-plugin-ci/releases/tag/4.0.0

Closing this now. Thanks to everybody!
