### ISSUE TITLE
Language Strings - Sorted

### ISSUE THREAD

**Issue by jrchamp** [moodlehq/moodle-plugin-ci#182]
Something that would be nice to catch as part of the automated tests would be to make sure that strings in the language files are sorted by their keys. It seems like it should be possible to detect this and throw a warning or error.

I know this would have saved me some time fixing a few commits after the original pull request had been merged.

**Comment by stronk7** [comment]
Hi @jrchamp,

I'm closing this in favour of https://github.com/moodlehq/moodle-cs/issues/8 , because it certainly seems to be something that PHP_CodeSniffer and the moodle standard should be able to check.
