### ISSUE TITLE
[Question] ---extra-plugins wrong versions.php path when validating plugin

### ISSUE THREAD

**Issue by colradectug** [moodlehq/moodle-plugin-ci#184]
I'm not really sure, if this behavior is intended and installing a single plugin works with the ```--plugin``` parameter. 

However, installing with the parameter ```--extra-plugins``` the path where the version.php is searched in, seems to be odd and is obviously wrong.

it searches for the file ```/path/to/moodle/local/testplugin/lang/version.php```. Is this lang path intended?

Best regards

Edit:
So it seems that in PluginInstaller.php:94 a directory is used and all folders in this directory are scanned and interpreted as single plugin (which requires a folder with only exactly these plugins, no additional ones). So I guess, this behavior is intended but useless for many usecases.

Edit2: I will write a script, that creates a dir and removes it after installing, so I will close this issue. Maybe a support for a CSV file with all paths for directories is an option for the future :)

**Comment by stronk7** [comment]
Hi @colradectug,

I'm not sure if I'm following your problems. Is this the case of a (target) plugin that, in order to work needs other (dependencies) plugins to be also installed... or what?

I'm curious why https://moodlehq.github.io/moodle-plugin-ci/AddExtraPlugins.html won't work for you...

**Comment by colradec** [comment]
hey @stronk7 

Sorry for the ultra late reply, but i wanted to add something to your reply and to your great moodle-plugin-ci.

We are a medium sized Team @TUGraz which uses Moodle for many huge Projects on different instances (e.g. Teachcenter and iMoox). As for now, we maintain >120 Plugins for those instances with a huge dependency tree. As our Servers are hosted elsewhere, we are not able to scale them up, this fact requires us to use the moodle-plugin-ci offline in our custom docker container. This environment is a self-setup with composer and lots of scripts to set up everything from moodle to the moodle-plugin-ci. 

As we are not pushing (but committing) onto the server until the offline moodle-plugin-ci runs without any errors, there are no branches which are up to date on the remote until validated. 

For this purpose i added some functionality to get folders and its contents and copy them into the CI (install command). As this works fine, however it is a total quirks and merging the new versions is lots of work. 

I thought, you are maybe interested in an additional command which is called add-offline-extra-plugins. It works exactly as add-extra-plugins but with copying and checking out the offline branches in the copied folders. I also wrote test cases with 100% coverage and added all needed documentation. [offline-plugin branch](https://github.com/colradec/moodle-plugin-ci/tree/offline-plugins/docs). It is a fork from your master-branch (19.4.2023)

Maybe you guys are interested in it and maybe there is a possibility to add this feature to the new 4.0 version of moodle-plugin-ci.

Cheers
Luca
