### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by gjb2048** [moodlehq/moodle-plugin-ci#188]
Ref, annotation notices on https://github.com/gjb2048/moodle-format_grid/actions/runs/3236667881

Leads to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ - but no idea how to solve this one!

**Comment by gjb2048** [comment]
Did a bit of digging and I think could be related to this development commit https://github.com/shivammathur/setup-php/commit/0575a32108978260a650e390d7008ce2c95b43e3

**Comment by stronk7** [comment]
Good one, I really couldn't imagine which action may be using that, because for sure we don't do it.

It seems that has been already fixed @ https://github.com/shivammathur/setup-php/issues/654 and will come to us automatically on next release.

Let's keep an eye on that!
