### ISSUE TITLE
Wrong year

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-plugin-ci#198]
Version [3.4.4](https://github.com/moodlehq/moodle-plugin-ci/compare/3.4.3...3.4.4) - shows 2022-01-20 as release date.  In this part of the world we are already 2023.

**Comment by kabalin** [comment]
Oh dear

**Comment by stronk7** [comment]
That's me, I'm afraid, it happens all the years, sorry!

**Comment by stronk7** [comment]
(though, I'm really improving because [in codechecker](https://github.com/moodlehq/moodle-local_codechecker/commit/1a5f491e5e0aae35370cbb395964aca981b51017), I did it ok!)
