### ISSUE TITLE
install overrides phpunit.xml file in project

### ISSUE THREAD

**Issue by Glutamat42** [moodlehq/moodle-plugin-ci#203]
When running moodle-plugin-ci (as it is the default in the provided github actions template) moodle-plugin-ci will create a new phpunit.xml file in the plugin directory, ignoring the one in my git repository. In my opinion this is counter-intuitive, because that way the pipeline is doing things differently than it is in every other environment and compared to how i configured it. 

In my case I have some files in the repo just for reference and some files containing common code in tests directory.  Both are included in the test coverage because of that issue. Also other options like `beStrictAboutOutputDuringTests` are different in the CI pipeline.

There is no option to disable only the phpunit.xml generation. As a workaround I'm currently using `moodle-plugin-ci install --no-init` and running `php admin/tool/phpunit/cli/init.php` manually.

**What i expected to happen**
- Using the phpunit.xml file in the repo (maybe with an exception if it differs from what is currently expected)
- Be clear about that issue in the documentation/logs
- Having a switch to disable phpunit.xml generation

**References**
- [Pipeline with the wrong phpunit.xml printed in step PHPUnit tests](https://github.com/ProjektAdLer/MoodlePlugin/actions/runs/4245418989/jobs/7380898537)
- [phpunit.xml in my repository](https://github.com/ProjektAdLer/MoodlePlugin/blob/927dc3a3ef28e0f6af39dd9585ecaa68e8081c46/phpunit.xml)
- [Workflow with workaround](https://github.com/ProjektAdLer/MoodlePlugin/blob/927dc3a3ef28e0f6af39dd9585ecaa68e8081c46/.github/workflows/moodle-ci.yml)

**Comment by paulholden** [comment]
Hi @Glutamat42 - just on the code coverage point, you can already achieve this without any changes, see https://docs.moodle.org/dev/Writing_PHPUnit_tests#Check_your_coverage and semi-recent improvements in that area at [MDL-72701](https://tracker.moodle.org/browse/MDL-72701)

**Comment by Glutamat42** [comment]
That is exactly what i am doing. I have this block in the phunit.xml file in the root directory of my plugin

```
<coverage>
    <include>
      <directory suffix=".php">classes</directory>
<!--      <directory suffix=".php">tests/generator</directory>-->
      <file>lib.php</file>
      <file>locallib.php</file>
      <file>renderer.php</file>
      <file>rsslib.php</file>
      <directory suffix=".php">backup/moodle2</directory>
    </include>
    <exclude>
      <directory suffix=".php">tests</directory>
      <directory suffix=".php">dev_utils</directory>
    </exclude>
  </coverage>
```
But moodle-plugin-ci is replacing the whole file with a new one (sounds like the behavior described in your link for pre 3.7). Moodle versions i used in the pipelines are 3.11 and 4.1

**Comment by paulholden** [comment]
No, define it in your plugin `tests/coverage.php` file - there is no need to define that in `phpunit.xml`

**Comment by Glutamat42** [comment]
Got it. Sadly this doesn't help me because there is no way setting the other config options during `admin/tool/phpunit/cli/util.php --buildcomponentconfigs`, so I'll still have to stick to my current approach.

**Comment by kiklop74** [comment]
Now I know why I could not enable testdox output for unit tests...

**Comment by stronk7** [comment]
Linking with #146, because we have to stop doing that, surely at the same time we fix this.

**Comment by stronk7** [comment]
What if, in order to solve this:

1. If no `phpunit.xml` file is present, it's generated normally (`--buildcomponentconfigs` will do).
2. If `phpunit.xml` is there, it won't be overwritten (surely by saving and restoring it after  `--buildcomponentconfigs`).
3. If the `phpunit.xml` is there, and it does not have coverage information, the `tests/coverage.php` information will be used if available. If not, the defaults will be used (this point may be complex to achieve).

May that 1-2 (and optionally 3) behaviour work, without needing to use any new option?

**Comment by stronk7** [comment]
FYI, I've created #216 that ensures points 1 & 2 above. Main detail being that, if a `phpunit.xml` file is present in the plugin base dir... it won't be overwritten or modified ever. The developer is in charge of managing it 100%.

Ciao :-)
