### ISSUE TITLE
Mustache lint warns when using #shortentext helper

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-plugin-ci#208]
Using the #shortentext helper in Mustache templates generates a warning:

   `<h3>{{#shortentext}} 25, {{name}} {{/shortentext}}</h3>`

(WARNING: HTML Validation info: Empty heading. (`<h3></h3>`)

**Comment by kabalin** [comment]
Thanks @ewallah, this is really an issue at linter that is not aware of `shortentext` helper (https://github.com/moodlehq/moodle-local_ci/blob/master/mustache_lint/mustache_lint.php#L89). You can temporally make it pass it by adding both `shortentext` and `name` to `Example context (json):` section at the header or the template, e.g.
```
{{!
    @template local_plugin/name

    Template for showing name

    Example context (json):
    {
        "shortentext": true,
        "name": "hello"
    }
}}
``` 
Closing as not related to moodle-plugin-ci. I created MDLSITE issue: https://tracker.moodle.org/browse/MDLSITE-7137

**Comment by ewallah** [comment]
THX for the nice workaround.
