### ISSUE TITLE
Use Symfony 4.4 (current LTS)

### ISSUE THREAD

**Issue by kabalin** [moodlehq/moodle-plugin-ci#21]
As Symfony 3.4 support comes to end in 11/2020, we need to switch Symfony packages to current LTS version: https://symfony.com/releases/4.4

**Comment by stronk7** [comment]
Pity about this is the Sympathy 4.4 requires php71. So:

- people will need to move their tests (matrix, jobs) up if they are still using php70.
- minimum compatible version of Moodle will be 3.2 (older don't support php71).

**Comment by stronk7** [comment]
Results with just versions and dependencies updated: https://travis-ci.org/github/stronk7/moodle-plugin-ci/builds/726331973

**Comment by stronk7** [comment]
Closing this is favor of #151 , that is using Symfony 5, already in master branch and near 4.0.0 release.
