### ISSUE TITLE
Deprecate phpdbg support

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#213]
Since PHP 8.0 `phpdbg` is causing more and more problems, like random crashes (#204). And things are worse in PHP 8.1... (in fact I think I've read somewhere that it was going to be removed, but I've failed to find the link).

In any case, the fact is that it is suboptimal when used for calculating code-coverage (the use we have of it). And, luckily, there are 2 good alternatives: `xdebug 3` (any version) and `pcov` (Moodle 3.10 and up), both supported by us since June 2022. Both are nicely documented, and easy to setup, see #212).

So this issue is about to agree to remove `phpdbg` support and do it.

Ciao :-)

**Comment by scara** [comment]
Hi Eloy,
do you mean https://github.com/sebastianbergmann/php-code-coverage/blob/10.0.0/ChangeLog.md#removed ?

HTH,
Matteo

**Comment by stronk7** [comment]
Ah, I didn't know that PHPUnit 10 is dropping support for it. Really it makes complete sense because it has become worse and worse on every php 8.x release, being practically unusable now.

So, yes, the idea is to start warning for sites still using in and, in one year or so, completely remove support to it, making the phpunit run to fail.

Ciao :-)

**Comment by stronk7** [comment]
Note / reminder: We must declare `phpdbg` deprecated ASAP (this issue, v4), because in the next v5 major version, if we want to jump to PHPUnit >= 10, we are going to need to remove & document any reference to it.
