### ISSUE TITLE
Add PHPUnit test component_test::test_get_component_classes_in_namespace

### ISSUE THREAD

**Issue by james-cnz** [moodlehq/moodle-plugin-ci#227]
Is it possible to add the PHPUnit test component_test::test_get_component_classes_in_namespace ?  I think it might be useful, because I've had two issues raised over this one check:
- https://github.com/james-cnz/moodle-format_multitopic/issues/25#issuecomment-1136538486
- https://github.com/james-cnz/moodle-format_multitopic/issues/39

**Comment by andrewnicols** [comment]
Hi James,

There's nothing stopping you from running this test in your GH workflow file.

**Comment by james-cnz** [comment]
Hi Andrew,

Thanks for responding.  Sorry, I don't really know what I'm doing.  I tried this, which is the argument I'd pass to PHPUnit if running it locally:
moodle-plugin-ci phpunit --filter test_get_component_classes_in_namespace
And it reported:
The "--filter" option does not exist.
And I didn't see anything about doing this in the docs.
Could you give me instructions for running this test?

**Comment by stronk7** [comment]
Hi,

note that we have #100 (nice number!) about to add support for `--filter` and others to the phpunit utility.

Right now, the only way to run other tests (from core or elsewhere) is to have a custom `phpunit.xml` file in the plugin. Only that way `moodle-plugin-ci` won't create its own, that defaults to the plugin own tests, logically.

Disclaimer: Note that I've not checked if it's possible to have a custom `phpunit.xml` pointing to tests elsewhere, so it may not work either.

Ciao :-)

**Comment by james-cnz** [comment]
Thanks, this works for me.
