### ISSUE TITLE
Themes that fallback on the theme/boost/template/head.mustache file, receive warnings

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-plugin-ci#233]
```
Run moodle-plugin-ci --ansi mustache
 RUN  Mustache Lint on theme_xxx
/home/runner/work/moodle-theme_xxx/moodle-theme_xxx/moodle/theme/xxx/templates/login.mustache - WARNING: HTML Validation info, line 5: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values. (itle>    <link rel="shortcut icon" href="favicon.ico" />    )
- OK: Mustache rendered html succesfully
Error: Process completed with exit code 1.
```
The issue was reported in [MDL-78809](https://tracker.moodle.org/browse/MDL-78809).

There is a simple workaround in GitHub Actions:
```
      - name: fix mustache
        run: sed -i 's/ \/>/ >/g' head.mustache
        working-directory: moodle/theme/boost/templates
```

**Comment by stronk7** [comment]
Hi @ewallah ,

just noting that, recently…see https://github.com/moodlehq/moodle-local_ci/pull/274, we have changed how “info” reports are managed, not leading to warnings/problems any more.

And it has been already released (today), so I bet this won’t be a problem anymore (no matter the MDL issue that is good to go).

I will keep this open, if you can confirm that new builds of your theme are now ok, that would be great!

Ciao :)

**Comment by ewallah** [comment]
The warning is still shown, but the error is gone:
```
Run moodle-plugin-ci --ansi mustache
 RUN  Mustache Lint on theme_xxx
/home/runner/work/moodle-theme_xxx/moodle-theme_xxx/moodle/theme/xxx/templates/login.mustache - WARNING: HTML Validation info, line 5: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values. (itle>    <link rel="shortcut icon" href="favicon.ico" />    )
/home/runner/work/moodle-theme_xxx/moodle-theme_xxx/moodle/theme/xxx/templates/core/block.mustache - OK: Mustache rendered html succesfully
```

THX

**Comment by stronk7** [comment]
Hi @ewallah ,

nice to see that the error is gone... but... there is something that I don't quit understand.

If you are using actual versions... then the output above should say: `INFO: HTML Validation info, line 5...` instead of `WARNING: HTML Validation info, line 5...`.

That's what https://github.com/moodlehq/moodle-local_ci/pull/274 did. So, something has become mixed at some point.

Q: Is the theme-xxx repo public? Or the GHA executions (complete log). Just to see what is being exactly executed because the outcome that you reported above makes no sense, it should be WARNING => problem, INFO => no problem.

**Comment by ewallah** [comment]
Sorry, but the repo is not public.

And indeed, the WARNING converted into a INFO message:

```
Run moodle-plugin-ci --ansi mustache
 RUN  Mustache Lint on theme_?????
/home/runner/work/moodle-theme_?????/moodle-theme_?????/moodle/theme/?????/templates/core/local/reactive/debugpanel.mustache - OK: Mustache rendered html succesfully
/home/runner/work/moodle-theme_?????/moodle-theme_?????/moodle/theme/?????/templates/core/block.mustache - OK: Mustache rendered html succesfully
/home/runner/work/moodle-theme_?????/moodle-theme_?????/moodle/theme/?????/templates/login.mustache - INFO: HTML Validation info, line 5: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values. (itle>    <link rel="shortcut icon" href="favicon.ico" />    )
/home/runner/work/moodle-theme_?????/moodle-theme_?????/moodle/theme/?????/templates/login.mustache - OK: Mustache rendered html succesfully
```

**Comment by stronk7** [comment]
Aha, ok, thanks for checking!

That `WARNING: HTML Validation info` was driving me crazy! Glad to see it's now `INFO: HTML Validation info` instead.

Ciao :-)
