### ISSUE TITLE
missing right --version message

### ISSUE THREAD

**Issue by kordan** [moodlehq/moodle-plugin-ci#252]
Once moodlepluginci is installed locally
by issuing:
../moodle-plugin-ci/vendor/bin/phpcs --version
I get:
PHP_CodeSniffer version 3.7.2 (stable) by Squiz (http://www.squiz.net)

but issuing:
../moodle-plugin-ci/vendor/bin/phpcbf  --version
I get:
PHP_CodeSniffer version 3.7.2 (stable) by Squiz (http://www.squiz.net)
too
While something like: PHP_Codebeautifiercodefixer is expected.

**Comment by kabalin** [comment]
That is possibly a question/bug report to https://github.com/squizlabs/PHP_CodeSniffer, looks like those scripts are calling different methods of the same class.

**Comment by kordan** [comment]
You are right.
I apologise.
