### ISSUE TITLE
moodle-plugin-ci phpcs fails: moodle coding standard not installed

### ISSUE THREAD

**Issue by PhMemmel** [moodlehq/moodle-plugin-ci#293]
When running `moodle-plugin-ci codechecker` in my local gitlab pipeline, the error is reported:

```
RUN  Moodle CodeSniffer standard on MY_PLUGINNAME
ERROR: the "moodle" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz and Zend
```

**Comment by stronk7** [comment]
It's working for me, so far: https://github.com/moodlehq/moodle-local_codechecker/actions/runs/8263285860

I'd recommend to take a look to logs, maybe there was some networking / gha / composer problem and that caused the standard not to be installed.

Ciao :-)
