### ISSUE TITLE
ERROR | Missing member variable doc comment (moodle.Commenting.VariableComment.Missing) reporting on constructor parameters.

### ISSUE THREAD

**Issue by gjb2048** [moodlehq/moodle-plugin-ci#295]
Initially reported here, then realised that https://github.com/moodlehq/moodle-cs/issues/143 is a better place for the issue.

Related to the change: https://github.com/moodlehq/moodle-plugin-ci/commit/c3f7ea8c1190bc6516076d2ba1a649a3de89a8cd#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R58 - though.

**Comment by stronk7** [comment]
Thanks for reporting, @gjb2048 .

As soon as https://github.com/moodlehq/moodle-cs/issues/142 is fixed, we'll make a new release here including it.

Ciao :-)

**Comment by stronk7** [comment]
Hi,

we have just released [moodle-plugin-ci 4.4.3](https://github.com/moodlehq/moodle-plugin-ci/releases/tag/4.4.3) that includes [moodle-cs v3.4.5](https://github.com/moodlehq/moodle-cs/releases/tag/v3.4.5) and has the `__construct()` issue fixed.

So, closing this now, ciao :-)

**Comment by gjb2048** [comment]
@stronk7 Thank you :)
