### ISSUE TITLE
False negative "incomplete parameters list" with optional function parameters

### ISSUE THREAD

**Issue by mk-kialo** [moodlehq/moodle-plugin-ci#315]
Hi! I'm using `moodlehq/moodle-plugin-ci`, version `^4.5.4` in the GitHub actions CI of a plugin,
and it seems to incorrectly cause an error about a allegedly missing docstring:

```
RUN  Moodle PHPDoc Checker on mod_kialo
/home/runner/work/moodle-mod_kialo/moodle-mod_kialo/moodle/mod/kialo/classes/lti_flow.php
    Line [13](https://github.com/kialo/moodle-mod_kialo/actions/runs/10595966762/job/29362879668#step:12:14)9: Phpdocs for function lti_flow::init_resource_link has incomplete parameters list (error)
```

The function in question is this:
```php
    /**
     * Initializes an LTI flow that ends up just taking the user to the target_link_uri on the tool (i.e. Kialo).
     *
     * @param int $courseid
     * @param int $coursemoduleid
     * @param string $deploymentid
     * @param string $moodleuserid
     * @param string $discussionurl
     * @param string|null $groupid
     * @param string|null $groupname
     * @return LtiMessageInterface
     * @throws LtiExceptionInterface
     * @throws \coding_exception
     * @throws \dml_exception
     */
    public static function init_resource_link(
        int $courseid,
        int $coursemoduleid,
        string $deploymentid,
        string $moodleuserid,
        string $discussionurl,
        ?string $groupid = null,
        ?string $groupname = null
    ): LtiMessageInterface {
   ...
}
```

It's apparently about the optional string arguments. If I make them non-optional (remove the default value, use `string` instead of `?string`, and only `string` instead of `string|null` in the PHPdoc ocmment) the check doesn't complain.

Is this a bug, or am I doing something wrong here?

**Comment by kabalin** [comment]
Hi @mk-kialo, the link to CI failure you posted is reflecting commit that has `string` only type: https://github.com/kialo/moodle-mod_kialo/blob/10d315bdc5d98f3e943eb85226d0e18ea911ce3b/classes/lti_flow.php#L144 Do you have CI run example where you actually try `@param null|string`? This test is a part of https://github.com/moodlehq/moodle-local_moodlecheck, so the bug needs to be reported there.

**Comment by mk-kialo** [comment]
Hi! Here is a build with the original code (using optional params both in PHPdoc and the PHP function signature): https://github.com/kialo/moodle-mod_kialo/actions/runs/10593100453/job/29353856529

The specific file at the corresponding revision: https://github.com/kialo/moodle-mod_kialo/blob/65b2d25a5a8e13e4eb72277f24c7008433ad1682/classes/lti_flow.php

I'll report the issue over at https://github.com/moodlehq/moodle-local_moodlecheck then, thanks

**Comment by mk-kialo** [comment]
Reported: https://github.com/moodlehq/moodle-plugin-ci/issues/315

**Comment by kabalin** [comment]
> Hi! Here is a build with the original code (using optional params both in PHPdoc and the PHP function signature): https://github.com/kialo/moodle-mod_kialo/actions/runs/10593100453/job/29353856529
> 
> The specific file at the corresponding revision: https://github.com/kialo/moodle-mod_kialo/blob/65b2d25a5a8e13e4eb72277f24c7008433ad1682/classes/lti_flow.php

But it got `int|null` at https://github.com/kialo/moodle-mod_kialo/blob/65b2d25a5a8e13e4eb72277f24c7008433ad1682/classes/lti_flow.php#L144
 
> I'll report the issue over at https://github.com/moodlehq/moodle-local_moodlecheck then, thanks
Thanks!

**Comment by mk-kialo** [comment]
Oh god... yes.... I completely missed that. That was the problem. 🤦 
Thank you so much @kabalin . Then this is a non-issue, my bad.
