### ISSUE TITLE
Backport node.js fix to v3 branch

### ISSUE THREAD

**Issue by jrchamp** [moodlehq/moodle-plugin-ci#316]
Can a similar fix be applied to the 3.x branch? We still do some testing against older versions which do not work with 4.x

_Originally posted by @jrchamp in https://github.com/moodlehq/moodle-plugin-ci/issues/309#issuecomment-2307513921_

**Comment by kabalin** [comment]
Thanks @jrchamp, we released the fix at https://github.com/moodlehq/moodle-plugin-ci/releases/tag/3.4.14
