### ISSUE TITLE
caniuse-lite deprecated

### ISSUE THREAD

**Issue by rezeau** [moodlehq/moodle-plugin-ci#318]
When running moodle-ci I get this error:
Running "eslint:amd" (eslint) task
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

**Comment by kabalin** [comment]
This is not a bug. Browserlist targets are not updated often, so it is common to see that notice.
