### ISSUE TITLE
I keep getting "File is stale and needs to be rebuilt"

### ISSUE THREAD

**Issue by rezeau** [moodlehq/moodle-plugin-ci#319]
I keep getting this GRUNT error message:
File is stale and needs to be rebuilt: amd/build/questionedit.min.js.map
File is stale and needs to be rebuilt: amd/build/questionedit.min.js
But I'm pretty sure both files are OK, they have the same datestamp as amd\src\questionedit.js
What can I do?

**Comment by rezeau** [comment]
Forgot to add this piece of info: grunt -version grunt-cli v1.4.3 grunt v1.6.1
I've found quite a few posts related to this error message on the Moodle forums and in the Tracker. Maybe my problem is due to moodle-ci using a different version from the one I'm using on my local installation?

**Comment by kabalin** [comment]
Hi, this means that version of node/dependencies you use locally are different to those used in Moodle version you run the test on.

Make sure your local version is matching, easiest way to do it is to run `nvm install && nvm use && npm install` from Moodle root, then navigate to your plugin dir and run `npx grunt amd`, and commit changes in minified files.

**Comment by kabalin** [comment]
> How do I know which of those versions I should use to be compatible with the moodle-ci test site?

Please refer to docs https://moodledev.io/general/development/tools/nodejs#install-nvm-and-node
