### ISSUE TITLE
MDL-82427 class alias usage for M4.5 filters fails validation.

### ISSUE THREAD

**Issue by gjb2048** [moodlehq/moodle-plugin-ci#321]
Hello,

Validation error: https://github.com/gjbarnard/moodle-filter_synhi/actions/runs/10983203114/job/30492304979#step:10:18 is caused because the validator is expecting filter_[pluginname] class located in filter/[pluginname]/filter.php

![Screenshot 2024-09-22 190143](https://github.com/user-attachments/assets/e963a032-9493-455a-aa50-598496ada0dd)

However this is now a class alias, please see: https://moodledev.io/docs/4.5/devupdate#filter-plugins:

![Screenshot 2024-09-22 190255](https://github.com/user-attachments/assets/8a68818d-a49b-4875-9f9f-6c60674cf233)

and 'MDL-82427 core: Update namespace of core_filters classes' being https://git.moodle.org/gw?p=moodle.git;a=commit;h=16456220cd7457d1c2db373559827f55b382a832 which belongs to https://tracker.moodle.org/browse/MDL-82706.

Cheers,

Gareth

**Comment by usantos-at-wiris** [comment]
We are having the exact same issue, thanks.
