### ISSUE TITLE
Drop support for "unsupported" Moodle versions

### ISSUE THREAD

**Issue by fulldecent** [moodlehq/moodle-plugin-ci#322]
Currently this tool claims to work for "Moodle 3.8.3 or later"

![Screenshot 2024-10-08 at 16 24 52](https://github.com/user-attachments/assets/1a4c03eb-22d9-4499-ad21-58efbc665d7f)

However according to the Moodle project, 4.1 is the "latest supported Moodle version". https://moodledev.io/general/releases

I would like to request please that this plugin CI and all other parts of Moodle will drop support for 4.0 and older versions. (And also PHP versions older than 8.1 https://www.php.net/supported-versions.php)

**This will align this project with Moodle's publicly stated version support policy.**

And this is important as it pushes this project into the future. And specifically it will reduce the burden on Moodle plugin authors. Today if a plugin author is evaluating where to spend resources, it may decide to focus on only "supported" Moodle versions, but that focus is muddled when Moodle's own projects support a wider range than what it claims is official support.

**Comment by fulldecent** [comment]
The reason why is because Moodle has an organization has made a decision. And when it makes decisions it should implement them.

Otherwise, we cannot take that organization seriously.

For example, like when Moodle says that its mission statement is that users will be able to use Moodle however they want—but then when you install Moodle it turns on telemetry and there is no obvious way to turn it of—we must then take Moodle HQ. 

I have made a separate issue for that item. And I have opened this item here. Hopefully in the future Moodle HQ can be more consistent internally and tell better truths.

---

As for plugin authors, they are welcome to use old versions of this tool. 

But it is my experience that plugins are failing to always support the latest version of Moodle and so clearly we should remove *some* burdens from plugin authors. And we should also encourage to move their attention to the newer versions.

**Comment by gjb2048** [comment]
@fulldecent RE: "But it is my experience that plugins are failing to always support the latest version of Moodle and so clearly we should remove some burdens from plugin authors. And we should also encourage to move their attention to the newer versions." what burdens with this tool?  I've already used it to create a version of Adaptable for Moodle 4.5 without any hinderance.  If a plugin is failing to support the 'latest' version of Moodle then it will be for other reasons not using this tool, so I still don't get what you're on about.

**Comment by fulldecent** [comment]
Here is one specific example of how supporting old versions of Moodle that we don't need to support impedes progress on this repo:

https://github.com/moodlehq/moodle-plugin-ci/blob/f722b93722902e4fc496fe2afa00e03230107f9f/.github/workflows/test.yml#L17-L20

**Comment by gjb2048** [comment]
@fulldecent I use xdebug in M4.1 to M4.5 development, so that line could be relevant beyond the wording of the comment.

**Comment by kabalin** [comment]
It is definitely at plugin developer discretion to decide which versions they need to support, not something we should force with this tool. Upcoming [v5](https://github.com/moodlehq/moodle-plugin-ci/milestone/1) will rise minimum Moodle version requirement due to tool dependencies.
