### ISSUE TITLE
Failed to find version.php

### ISSUE THREAD

**Issue by danbuntu** [moodlehq/moodle-plugin-ci#328]
Hello

I'm new to github actions so really happy that this project exists as a nice starter

My plugin repo is structured like

<repo name>/<plugin folder>/version.php

Ie the repo contains a folder with the plugin code so that we can quickly pick up and deploy the folder.

When I run the CI I get

 Failed to find '/home/runner/work/<repo name>/<plugin name>/plugin/version.php' file. 

Is this because of my repo/folder structure? Is there a change I need to make in the yaml to resolve this?

**Comment by kabalin** [comment]
Hi @danbuntu, thanks, using `--plugin ./plugin/foldername` param for install command and specifying your folder should do the job (https://github.com/moodlehq/moodle-plugin-ci/blob/main/gha.dist.yml#L62)

It is usually better not to use folder in the plugin repo unless you really have good reason, it makes easier for someone to maintain your plugin as part of another repo used for deployment.
