### ISSUE TITLE
Move a note in the "Release new version" page to earlier in the doc

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#43]
There is a note in the [Release new version](https://moodlehq.github.io/moodle-plugin-ci/ReleaseNewVersion) page:

> Note: Before sending the tag upstream, make sure that Travis is not running any builds, otherwise tag build might not get triggered. If this happenened, you need to remove tag and push it again when Travis is not busy.

But, right now it too later in the page. Ideally, it should be warned *before* the {{git push}} of the new tag is performed, so better we move it there.

Just a tiny detail.

**Comment by emily-ng** [comment]
Hi! I'd like to help with this task.
