### ISSUE TITLE
Travis-CI alternatives ?

### ISSUE THREAD

**Issue by ak4t0sh** [moodlehq/moodle-plugin-ci#47]
I create this issue following Travis-CI pricing changes annoucement : https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
As you can read "Free Plan" will give you 10k credits (~1k minutes on Linux environment) then you need to pay 69$/month. 

I recently created #39 to add gitlab-ci support but maybe others alternatives like Github Actions (which include 2k minutes/month on their free plan) should be added too.

My concern here is that independent developers stop testing their plugins once their free plan consumed.

Pinging plugins curator @mudrd8mz and @danmarsden

**Comment by mudrd8mz** [comment]
Well, as far as I know, we never and nowhere _demanded_ that Travis-CI must be used. CI is a recommended industry standard workflow. Whether CI is performed on travis, gitlab, github or folks' private infrastructure, is not relevant. IMHO.

**Comment by ak4t0sh** [comment]
I agree that implementing CI is not required but nowadays this is a kind of "best practice" implemented by a lot of plugin developers.
But maybe I'm wrong and there is not so much plugins implementing CI. The only stats I could find is plugin with "Automated testing support" badge (https://moodle.org/plugins/browse.php?list=award&id=5) but it is only for those which implements PHPUnit/Behat tests.
Moreover Travis-CI is currently the only CI tools with an official dist file and documentation page (https://docs.moodle.org/dev/Travis_integration) it is currently the "de facto" CI tool when you start moodle plugins development. 
I created this issue to discuss about alternatives because IMHO it would be regrettable that developers stop implementing this best practice only because Travis changes their pricing plan. :)

**Comment by kabalin** [comment]
> My concern here is that independent developers stop testing their plugins once their free plan consumed.

Busy plugin developers may exceed those 16h per month, but for most contributors I guess that will be more than enough. Also there is an option to request extra free slots should one need them:

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

The rationale for pricing model is "abusing" free option, which is undestandable really:

>However, in recent months we have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators etc.). Abusers have been tying up our build queues and causing performance reductions for everyone.

**Comment by ak4t0sh** [comment]
Hi @kabalin 

I completly understand the "abusing" cases but :
> Busy plugin developers may exceed those 16h per month, but for most contributors I guess that will be more than enough.

Indeed 16h per month is more than enough for most developers and maybe I misread but at first sight that is not **16h per month** but **16h**.
https://travis-ci.com/plans
> New customers are assigned the Free plan by default. You will be given 10,000 credits to try out the system. Linux, Windows, macOS builds all supported. 

And from the announcement : 

> * For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> [...]
> * When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.

**Comment by kabalin** [comment]
> Indeed 16h per month is more than enough for most developers and maybe I misread but at first sight that is not **16h per month** but **16h** and then you have to pay or ask for extra slots.
> https://travis-ci.com/plans
> 
> > New customers are assigned the Free plan by default. You will be given 10,000 credits to try out the system. Linux, Windows, macOS builds all supported.
> 
> And from the announcement :
> 
> > * For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> >   [...]
> > * When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.

Oh, you are right, I misread this (or rather assumed that plan is something that supposed to recur). This can be a game-stopper indeed.
![travis](https://user-images.githubusercontent.com/329780/98370252-34218e00-2032-11eb-894b-6251f7372a51.jpeg)

**Comment by mudrd8mz** [comment]
> I created this issue to discuss about alternatives because IMHO it would be regrettable that developers stop implementing this best practice only because Travis changes their pricing plan

Any CI needs computing resources and all computing resources costs money. Getting resources for free is not longitudinally sustainable.

**Comment by danmarsden** [comment]
yeah - travis-ci integration has never been a requirement in the plugins db - there are several developers who host outside github so travis isn't even an option.

I do strongly encourage devs to enable it when I run through the review but with the latest annoucements I'll be careful considering how I word that request.

I'm suprised it's been free for so long tbh - it looks like there are some methods to allow open source devs to request more "free" credits, but it's not yet clear how this will work - something to watch! :-)

**Comment by kabalin** [comment]
> Github Actions (which include 2k minutes/month on their free plan) should be added too.

Not sure if this is their responce to Travis (I was sure I saw 2k mins free plan in the past too):
![Screenshot](https://user-images.githubusercontent.com/329780/98547936-d0e16700-2290-11eb-9733-9d5382a236ff.png)

It is totally free for public repos, may be we should look into make it usable with `moodle-plugin-ci`, so people can add it with little effort.

**Comment by rlorenzo** [comment]
FWIW the R project is going towards Github Actions: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

**Comment by stronk7** [comment]
Hi,

I'm closing this as far as #48, #72... are already part of released [moodle-plugin-ci 3.0.4](https://github.com/moodlehq/moodle-plugin-ci/releases/tag/3.0.4) and GHA is supported and working.

Of course, any contribution adding support (mainly instructions and example files, moodle-plugin-ci tries to be as much CI agnostic as possible, working on any environment) for other CI environments (gitlab, circleci, jenkins...) is welcome. Any time!

Ciao :-)
