### ISSUE TITLE
Implement GitHub workflow for moodle-plugin-ci self test.

### ISSUE THREAD

**Issue by kabalin** [moodlehq/moodle-plugin-ci#54]
Following #48 which demonstrated how GitHub actions can be used with `moodle-plugin-ci`, it probably makes sense moving testing of `moodle-plugin-ci` itself along with release stage to GitHub actions (basically re-implementing what is currently done in `.travis.yml`).

**Comment by stronk7** [comment]
Closing this because of #55 already landed, yay!
