### ISSUE TITLE
add-plugin action should not assume the default branch of a plugin is called 'master'

### ISSUE THREAD

**Issue by timhunt** [moodlehq/moodle-plugin-ci#58]
https://github.com/moodlehq/moodle-plugin-ci/blob/master/src/Command/AddPluginCommand.php

If --branch option is not given on the command-line (e.g. `moodle-plugin-ci add-plugin --branch main moodleou/moodle-filter_embedquestion`) then this plugin passes the branch name 'master' in the git clone command it runs. In this case, it would be better if it could just not add that argument, so that the install would use the default branch, whatever it is called (e.g. main).

**Comment by kabalin** [comment]
Thanks @timhunt, this has been addressed in the latest release.
