### ISSUE TITLE
Github workflows: code coverage run is using OS installed version of phpdbg

### ISSUE THREAD

**Issue by kabalin** [moodlehq/moodle-plugin-ci#62]
We are using `setup-php` action as part of the test workflow to select PHP version to use in the test. This apparently is not installing `phpdbg` of required version, thus in the phpunit test with text coverage report `phpdbg` of the OS installed version is used. When selected PHP version is one of supported by virtual environment (e.g. `ubuntu-18.04` supports [7.1, 7.2, 7.3, 7.4, 8.0](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#php)), you will get `phpdbg` matching the version you need. If virtual environment does not support requested PHP version, default OS version of `phpdbg` will be used (which is [PHP 8 for `ubuntu-18.04`](https://github.com/actions/virtual-environments/pull/2162)).

The issue has been picked in PR recently (https://github.com/moodlehq/moodle-plugin-ci/pull/60/checks?check_run_id=1591121986) when selected PHP version for test was 7.0 and environment set to `ubuntu-18.04`.

The current workaround for someone who needs coverage report with phpunit test on PHP 7.0 is to switch to `ubuntu-16.04` environment (per https://github.com/shivammathur/setup-php/issues/384#issuecomment-750358328) - this has PHP 7.0 installed, thus the version of `phpdbg` matching selected PHP version will be picked.

**Comment by kabalin** [comment]
To check which version of PHP is available in your chosen environment, see https://github.com/actions/virtual-environments/#available-environments

**Comment by stronk7** [comment]
Hi,

I think that, with #166 we can consider this fixed, as far as pcov => xdebug => phpdbg can be used and the docs already tell how to use the preferred ones?

**Comment by stronk7** [comment]
Closing this now, as agreed. #166 fixed it.
