### ISSUE TITLE
How do we ignore files using GitHub actions?

### ISSUE THREAD

**Issue by mchurchward** [moodlehq/moodle-plugin-ci#63]
Some code style issues are unavoidable. For example, extending the core PDF library means using functions that are not all lowercase. Previously, using Travis, we could [exclude a file](https://moodlehq.github.io/moodle-plugin-ci/IgnoringFiles.html). With the switch to GitHub actions, it does not seem possible to do this. Is there a way to do this in GH Actions?

**Comment by stronk7** [comment]
Maybe this is what you're looking for? Haven't tried 

https://docs.github.com/en/actions/reference/environment-variables

I think I experimented with them when working on [core GHA](https://github.com/moodle/moodle/blob/master/.github/workflows/push.yml) although finally didn't use them. But remember that they worked as expected.

Ciao :-)

**Comment by kabalin** [comment]
> With the switch to GitHub actions, it does not seem possible to do this. Is there a way to do this in GH Actions?

Those `IGNORE_*` env vars should work as expected, we are using them in fact https://github.com/moodlehq/moodle-plugin-ci/blob/master/.github/workflows/test.yml#L96.

**Comment by mchurchward** [comment]
> > With the switch to GitHub actions, it does not seem possible to do this. Is there a way to do this in GH Actions?
> 
> Those `IGNORE_*` env vars should work as expected, we are using them in fact https://github.com/moodlehq/moodle-plugin-ci/blob/master/.github/workflows/test.yml#L96.

Thanks. Location is everything. Putting it in the right place made all the difference. Thanks for the example.
