### ISSUE TITLE
Q: Should we ask for moodle-plugin-ci.phar to become .gitignored by moodle core

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#77]
It's really helpful to have `moodle-plugin-ci.phar` (or the whole repo and binary checkout too, of course) put in moodle dirrot.

That way you can basically run all moodle-plugin-ci commands locally, script them...

A little annoyance is that `git status` does warn you about the phar file not being in git. 

Of course, that ignore can be added locally to `.git/info/exclude` ... just asking if we should consider getting it added to distributed [moodlehq/moodle/.gitignore](https://github.com/moodle/moodle/blob/master/.gitignore) core.

I'm undecided... so asking for opinions... ciao :-)

**Comment by kabalin** [comment]
I think it won't harm really to have it in core `.gitignore` file, makes things a bit better for  someone who is using it that way, so +1.

**Comment by stronk7** [comment]
Have created https://tracker.moodle.org/browse/MDL-71004 about this, let's see what those moodlers think! 😛

**Comment by kabalin** [comment]
> let's see what those moodlers think!

Indded, you never know. Thanks!

**Comment by stronk7** [comment]
Closing this as far as https://tracker.moodle.org/browse/MDL-71004 has landed.
