### ISSUE TITLE
Consider which should be the next version to release

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#9]
There are already some good changes since the previous 2.5.0 release.

This issue is about to decide if we continue within the 2.x series or jump straight to 3.x. Some considerations:

- There are some noticeable changes to the .travis.dist.yml file
- It would be a good moment to check it's passing the new (beta) travis configuration checks.
- There were some comments in [the tracker](https://tracker.moodle.org/browse/MDLSITE-6102) suggesting that the major bump may make thing clearer.

Ciao :-)

**Comment by mudrd8mz** [comment]
+1 for the major dump - it will only makes things clearer. Especially as there significant changes.

**Comment by kabalin** [comment]
+1 for the major dump too.

**Comment by stronk7** [comment]
+1 here too for starting a new 3.x series

**Comment by stronk7** [comment]
Habemus [3.0.0](https://github.com/moodlehq/moodle-plugin-ci/releases/tag/3.0.0) release, so this can be now closed.

Thanks all!
