### ISSUE TITLE
Add php 8.0 support

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#94]
Right now it seems that php 8.0 is not well supported by moodle-plugin-ci

1) I tried bumping a plugin ([local_codechecker](https://github.com/moodlehq/moodle-local_codechecker/pull/145)) to 8.0 and started getting problems on install.
2) moodle-plugin-ci own tests (make, travis/gha...) are also failing badly.

So this is about to try to get everything working and passing with php 8.0. Sure that a bunch of dependencies will have to be updated too (phpunit, cs-fixer...) some only dev-dependencies but still.

Maybe, also, worth considering if we should drop support for 35_STABLE (and older) as far as it's (LTS) finished upstream (since May 10th, 2021).

This can be considered part of the [php80 epic](https://tracker.moodle.org/browse/MDL-70745).

Once fixed, we should release a new version ASAP. 

Ciao :-)

**Comment by ewallah** [comment]
With GitHub Actions code coverage is working in PHP 8.0 and PHP 7.4 in master and MOODLE_311_STABLE branches when 
- [using](https://github.com/ewallah/moodle-availability_language/blob/main/.github/workflows/main.yml#L54): `coverage: xdebug`
- [removing](https://github.com/ewallah/moodle-availability_language/blob/main/.github/workflows/main.yml#L69): `phpdbg -d memory_limit=-1 -qrr` from ci/src/Command/PHPUnitCommand.php file

In branches MOODLE_310_STABLE on PHP 7.4 and MOODLE_39_STABLE on PHP 7.3 the code coverage is ignored with the `Error:         Incorrect whitelist config, no code coverage will be generated.`

Perhaps this approach can shed some light on the segmentation faults?

**Comment by ewallah** [comment]
The segmentation faults when generating code coverage seems to be in the CodeUnitCollection class:

`SebastianBergmann\CodeUnit\CodeUnitCollection::mergeWith(): Argument #1 ($filename) must be of type string, SebastianBergmann\CodeUnit\CodeUnitCollection given, called in vendor/phpunit/phpunit/src/Util/Test.php on line 654`

**Comment by andrewnicols** [comment]
> The segmentation faults when generating code coverage seems to be in the CodeUnitCollection class:

Don't use `phpdbg`. The segfault is not an issue on our end, but in phpdbg.

When we first started supporting coverage generation from within Moodle, there was a choice between xdebug version 2, and nothing. xdebug at that time would take a _very_ long time to run, so when phpdbg was made more widely available we jumped at that as it gave code coverage generation in a fraction of the time.

Sadly, phpdbg is no good for coverage generation any more (it segfaults but there are other issues).

From Moodle 3.10 onwards we've been able to use `pcov` instead. It's easy to install, and run, and it's very fast. You can also use xdebug 3.

Don't bother with phpdbg. It's out our hands and there's very little that we can do except report the issues upstream with stacktraces.

**Comment by stronk7** [comment]
Please, let's create some issue about the problems with `phpdbg` and review that everything recommends to use `pcov` or `xdebug`.

Other than that', unless I'm missing something (please tell!), I think that we can close this because moodle-plugin-ci checks are working under php80 perfectly (but self-tests, but that's another story that will be touched @ #151).

Ciao :-)

**Comment by stronk7** [comment]
Hi,

I think that we can safely close this now.

- moodle-plugin-ci is perfectly able to run with php80.
- the phpdbg/coverage problems should be fixed because support for pcov/xdebug coverage were added by https://github.com/moodlehq/moodle-plugin-ci/pull/166 and they have been released.

Other than that, I imagine that, soon, we'll bump the requirements of moodle-plugin-ci to more actual versions (php, symfony...) but, as commented above, that's https://github.com/moodlehq/moodle-plugin-ci/issues/151

If nobody argues against it, I'll close this in 24h.

Ciao :-)
