### ISSUE TITLE
Bump GHA used ubuntu version (to 18.04 or 20.04)

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-plugin-ci#96]
Recent runs have started to warn:

```
Ubuntu 16.04 is deprecated. Please upgrade to Ubuntu 18.04 or Ubuntu 20.04 - https://setup-php.com/i/452
```

So we need to update own tests to some of them. And, maybe, also consider if we change gha.dist.yml (currently using 18.04).

Ciao :-)

**Comment by kabalin** [comment]
Just beware we should not run coverage test on PHP 7.0 after bumping OS to 18.04 (#62). And I see you removed it in commit already 👍

**Comment by stronk7** [comment]
Unless I'm wrong, I think that #183 should have closed this, but it seems I didn't use the correct closing sentence (or added it too late).

Hence, closing this now. Ciao :-)
