### ISSUE TITLE
Validate command fails on PHP 8

### ISSUE THREAD

**Issue by marinaglancy** [moodlehq/moodle-plugin-ci#98]
We have a strange failure for the validate command on one of workplace plugins (in gitlab CI):

```
$ . check moodle-plugin-ci validate
 RUN  Validating tool_dynamicrule
Warning: Undefined array key 312 in /var/www/html/ci/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 258
Warning: Undefined array key "" in /var/www/html/ci/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 190
Warning: Undefined array key "" in /var/www/html/ci/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 359
Warning: Undefined array key 312 in /var/www/html/ci/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 258
Warning: Undefined array key "" in /var/www/html/ci/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 190
Warning: Undefined array key "" in /var/www/html/ci/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 359
> Found required file: version.php
> Found required file: lang/en/tool_dynamicrule.php
X Failed to parse /builds/workplace/moodle/admin/tool/dynamicrule/db/upgrade.php file due to parse error: Syntax error, unexpected  on line 85
> In lang/en/tool_dynamicrule.php, found language pluginname
> In db/install.xml, found table prefixes tool_dynamicrule
....
```

The rest of the log is fine. 

The line 85 in admin/tool/dynamicrule/db/upgrade.php is:

```
        \tool_tenant\manager::create_workplace_role('tool_dynamicrule_manager',
```

There is nothing wrong with this line, it's the beginning of the function call spread over several lines.

The same plugin does not produce any errors on PHP 7

**Comment by marinaglancy** [comment]
in another plugin it complains about the line
{code}
$handler = tool_certificate\customfield\issue_handler::create();
{code}

I can see some pattern here...

**Comment by marinaglancy** [comment]
seems relevant:
https://github.com/maglnet/ComposerRequireChecker/issues/234

**Comment by stronk7** [comment]
Hi @marinaglancy ,

maybe, once #99 is reviewed and, hopefully lands... you can try with your plugin pointing to dev-master (instead of ^3). That way it will use the latest code that comes with an update of the php-parser from versions 3.x to 4.x (that in theory supports php80).

Let's see...

**Comment by marinaglancy** [comment]
yes, confirming that #99 fixed it! Thanks!
